### PR TITLE
Bodge guarding against issue #20

### LINKED ISSUE #20: @Lazy property wrapper is loaded eagerly
This is a test that ensures the `init` of a class isn't run when being stored at an `@Lazy` property. The test fails (and matches what I saw in real world usage), which looks like the property is loaded eagerly.

```swift
import XCTest
@testable import LazyContainers

var shouldNotRun = false

class ShouldNotInit {
    init() {
        shouldNotRun = true
    }
}

final class LazyContainersTests: XCTestCase {

    @Lazy
    var lazyShouldNotRun = ShouldNotInit()
    
    func testLazyInitWithPropertyWrapper() {
        XCTAssertFalse(shouldNotRun)
    }

    static var allTests = [
        ("testLazyInitWithPropertyWrapper", testLazyInitWithPropertyWrapper)
    ]
}
```

### PR DESCRIPTION
**Pull request by BenLeggiero**
This technically resolves #20, but I wish I could find a better solution.

### CODE REVIEW

File: Tests/LazyContainersTests/GitHubIssue20Tests.swift [hunk 1]
```diff
@@ -0,0 +1,39 @@
+//
+//  GitHubIssue20Tests.swift
+//  LazyContainersTests
+//
+//  Created by Ben Leggiero on 2020-07-29.
```
Comment (BenLeggiero) [inline Tests/LazyContainersTests/GitHubIssue20Tests.swift]: Copyright line
